mysite/autos/urls.py
from django.urls import path
from . import views


app_name = 'autos'
urlpatterns = [
    path('', views.MainView.as_view(), name='all'),
    path('lookup/', views.MakeView.as_view(), name='make_list'),
    path('lookup/create/', views.MakeCreate.as_view(), name='make_create'),
    path('lookup/<int:pk>/update/', views.MakeUpdate.as_view(), name='make_update'),
    path('lookup/<int:pk>/delete/', views.MakeDelete.as_view(), name='make_delete'),
    path('main/create/', views.AutoCreate.as_view(), name='auto_create'),
    path('main/<int:pk>/update/', views.AutoUpdate.as_view(), name='auto_update'),
    path('main/<int:pk>/delete/', views.AutoDelete.as_view(), name='auto_delete'),
]

mysite/cats/urls.py
from django.urls import path
from . import views


app_name = 'cats'
urlpatterns = [
    path('', views.MainView.as_view(), name='all'),
    path('lookup/', views.BreedView.as_view(), name='breed_list'),
    path('lookup/create/', views.BreedCreate.as_view(), name='breed_create'),
    path('lookup/<int:pk>/update/', views.BreedUpdate.as_view(), name='breed_update'),
    path('lookup/<int:pk>/delete/', views.BreedDelete.as_view(), name='breed_delete'),
    path('main/create/', views.CatCreate.as_view(), name='cat_create'),
    path('main/<int:pk>/update/', views.CatUpdate.as_view(), name='cat_update'),
    path('main/<int:pk>/delete/', views.CatDelete.as_view(), name='cat_delete'),
]

mysite/mysite/urls.py
import os
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.views.static import serve
from django.views.generic import TemplateView

# Up two folders to serve "site" content
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE_ROOT = os.path.join(BASE_DIR, 'site')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('hello/', include('hello.urls')),
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': SITE_ROOT, 'show_indexes': True},
        name='site_path'
    ),
    path('accounts/', include('django.contrib.auth.urls')),
    path('autos/', include('autos.urls')),
    path('cats/', include('cats.urls')),
    path('', TemplateView.as_view(template_name='home/main.html'), name='home'),
]

mysite/autos/models.py
from django.db import models
from django.core.validators import MinLengthValidator, MaxValueValidator


class Make(models.Model):
    name = models.CharField(max_length=128, validators=[MinLengthValidator(2, "Please enter a name with 2 or more characters")])

    def __str__(self):
        return self.name


class Auto(models.Model):
    nickname = models.CharField(max_length=128, validators=[MinLengthValidator(2, "Please enter a nickname with 2 or more characters")])
    make = models.ForeignKey('Make', on_delete=models.CASCADE, null=False)
    mileage = models.PositiveIntegerField(validators=[MaxValueValidator(999999, "Please enter a number less than 1000000")])
    comments = models.CharField(max_length=512)

    def __str__(self):
        return self.nickname

mysite/autos/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from autos.models import Auto, Make


# front page... autos/
class MainView(LoginRequiredMixin, View):
    def get(self, request):
        template_name = 'autos/auto_list.html'
        # info needed: list of autos and the make count
        auto_list = Auto.objects.all()
        make_count = Make.objects.all().count()

        # give them a key-value pair for template
        ctx = {'make_count': make_count, 'auto_list': auto_list}

        # return view
        return render(request, template_name, ctx)


# make list page... autos/lookup/
class MakeView(LoginRequiredMixin, View):
    def get(self, request):
        template_name = 'autos/make_list.html'
        # info needed: list of makes
        make_list = Make.objects.all()
        ctx = {'make_list': make_list}
        return render(request, template_name, ctx)


# Make Section: Add, Update, Delete


class MakeCreate(LoginRequiredMixin, CreateView):
    model = Make
    fields = '__all__'
    success_url = reverse_lazy('autos:all')


class MakeUpdate(LoginRequiredMixin, UpdateView):
    model = Make
    fields = '__all__'
    success_url = reverse_lazy('autos:all')


class MakeDelete(LoginRequiredMixin, DeleteView):
    model = Make
    fields = '__all__'
    success_url = reverse_lazy('autos:all')


# Auto Section: Add, Update, Delete

class AutoCreate(LoginRequiredMixin, CreateView):
    model = Auto
    fields = '__all__'
    success_url = reverse_lazy('autos:all')


class AutoUpdate(LoginRequiredMixin, UpdateView):
    model = Auto
    fields = '__all__'
    success_url = reverse_lazy('autos:all')


class AutoDelete(LoginRequiredMixin, DeleteView):
    model = Auto
    fields = '__all__'
    success_url = reverse_lazy('autos:all')

mysite/autos/templates/autos/auto_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Delete Auto</h1>

<p>Are you sure you want to delete the auto: {{ auto }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

mysite/autos/templates/autos/auto_form.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <br/>
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <br/>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'autos:all' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

mysite/autos/templates/autos/auto_list.html
{% extends "base_bootstrap.html" %}

{% block content %}
    <!-- List of Autos -->
    <h1>Auto List</h1>
    <p>This is an application to maintain a list of autos.</p>
    {% if auto_list %}
    <ul>
        {% for auto in auto_list %}
           <li>
               {{ auto.nickname }} ({{ auto.make }})
                (<a href="{% url 'autos:auto_update' auto.id %}">Update</a> |
                <a href="{% url 'autos:auto_delete' auto.id %}">Delete</a>) <br/>
                Comment: {{ auto.comments }} <br/> Mileage: {{ auto.mileage }} miles
            </li>
        {% endfor %}
    </ul>
    {% else %}
        <p>There are no autos in the library.</p>
    {% endif %}
    <!-- Rest of page -->
    <p>
    {% if make_count > 0 %}
        <a href="{% url 'autos:auto_create' %}">Add an auto</a>
    {% else %}
        Please add a make before you add an auto.
    {% endif %}
    </p>
    <p><a href="{% url 'autos:make_list' %}">View makes</a> ({{ make_count }}) |
    <a href="{% url 'autos:make_create' %}">Add a make</a></p>
{% endblock %}

mysite/autos/templates/autos/make_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Delete Make</h1>

<p>Are you sure you want to delete the make: {{ make }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
  <input type="submit" onclick="window.location='{% url 'autos:all' %}' ; return false;" value="Cancel">
</form>

{% endblock %}

mysite/autos/templates/autos/make_form.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <br/>
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <br/>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'autos:all' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

mysite/autos/templates/autos/make_list.html
{% extends "base_bootstrap.html" %}

{% block content %}
    <!-- List of Makes -->
    <h1>Makes List</h1>
    {% if make_list %}
    <ul>
        {% for make in make_list %}
           <li>
               {{ make.name }}
                (<a href="{% url 'autos:make_update' make.id %}">Update</a> |
                <a href="{% url 'autos:make_delete' make.id %}">Delete</a>) <br/>
            </li>
        {% endfor %}
    </ul>
    {% else %}
        <p>There are no makes in the library.</p>
    {% endif %}
    <!-- Rest of page -->
    <p><a href="{% url 'autos:make_create' %}">Add a make</a></p>
    <p><a href="{% url 'autos:all' %}">Back to autos</a></p>
{% endblock %}