mysite/cats/urls.py
from django.urls import path
from . import views


app_name = 'cats'
urlpatterns = [
    path('', views.MainView.as_view(), name='all'),
    path('lookup/', views.BreedView.as_view(), name='breed_list'),
    path('lookup/create/', views.BreedCreate.as_view(), name='breed_create'),
    path('lookup/<int:pk>/update/', views.BreedUpdate.as_view(), name='breed_update'),
    path('lookup/<int:pk>/delete/', views.BreedDelete.as_view(), name='breed_delete'),
    path('main/create/', views.CatCreate.as_view(), name='cat_create'),
    path('main/<int:pk>/update/', views.CatUpdate.as_view(), name='cat_update'),
    path('main/<int:pk>/delete/', views.CatDelete.as_view(), name='cat_delete'),
]

mysite/mysite/urls.py
import os
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.views.static import serve
from django.views.generic import TemplateView

# Up two folders to serve "site" content
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE_ROOT = os.path.join(BASE_DIR, 'site')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('hello/', include('hello.urls')),
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': SITE_ROOT, 'show_indexes': True},
        name='site_path'
    ),
    path('accounts/', include('django.contrib.auth.urls')),
    path('autos/', include('autos.urls')),
    path('cats/', include('cats.urls')),
    path('', TemplateView.as_view(template_name='home/main.html'), name='home'),
]

mysite/cats/models.py
from django.db import models
from django.core.validators import MinLengthValidator, MaxValueValidator, URLValidator

class Breed(models.Model):
    name = models.CharField(
            max_length=128,
            validators=[MinLengthValidator(2, "Please enter a name with 2 or more characters")]
    )

    def __str__(self):
        return self.name

class Cat(models.Model):
    nickname = models.CharField(
            max_length=128,
            validators=[MinLengthValidator(2, "Please enter a nickname with 2 or more characters")]
    )
    weight = models.PositiveIntegerField(validators=[MaxValueValidator(9999, "Please enter a number less than 10000")])
    foods = models.CharField(max_length=300)
    breed = models.ForeignKey('Breed', on_delete=models.CASCADE, null=False)
    image = models.URLField(max_length = 200, null=True,
                            validators=[URLValidator(regex="(.*imgur.*)", message="Please enter a link from imgur")])

    def __str__(self):
        return self.nickname

mysite/cats/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from cats.models import Cat, Breed

# front page... cats/
class MainView(LoginRequiredMixin, View):
    def get(self, request):
        template_name = 'cats/cat_list.html'
        # info needed: list of cats and the breed count
        cat_list = Cat.objects.all()
        breed_count = Breed.objects.all().count()

        # give them a key-value pair for template
        ctx = {'breed_count': breed_count, 'cat_list': cat_list}

        # return view
        return render(request, template_name, ctx)


# breed list page... cats/lookup/
class BreedView(LoginRequiredMixin, View):
    def get(self, request):
        template_name = 'cats/breed_list.html'
        # info needed: list of breeds
        breed_list = Breed.objects.all()
        ctx = {'breed_list': breed_list}
        return render(request, template_name, ctx)


# Breed Section: Create, Update, Delete


class BreedCreate(LoginRequiredMixin, CreateView):
    model = Breed
    fields = '__all__'
    success_url = reverse_lazy('cats:all')


class BreedUpdate(LoginRequiredMixin, UpdateView):
    model = Breed
    fields = '__all__'
    success_url = reverse_lazy('cats:all')


class BreedDelete(LoginRequiredMixin, DeleteView):
    model = Breed
    fields = '__all__'
    success_url = reverse_lazy('cats:all')


# Cat Section: Create, Update, Delete

class CatCreate(LoginRequiredMixin, CreateView):
    model = Cat
    fields = '__all__'
    success_url = reverse_lazy('cats:all')


class CatUpdate(LoginRequiredMixin, UpdateView):
    model = Cat
    fields = '__all__'
    success_url = reverse_lazy('cats:all')


class CatDelete(LoginRequiredMixin, DeleteView):
    model = Cat
    fields = '__all__'
    success_url = reverse_lazy('cats:all')

mysite/cats/templates/cats/breed_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Delete Breed</h1>

<p>Are you sure you want to delete the breed: {{ breed }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
  <input type="submit" onclick="window.location='{% url 'cats:all' %}' ; return false;" value="Cancel">
</form>

{% endblock %}

mysite/cats/templates/cats/breed_form.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <br/>
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <br/>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'cats:all' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

mysite/cats/templates/cats/breed_list.html
{% extends "base_bootstrap.html" %}

{% block content %}
    <!-- List of Breeds -->
    <h1>Breeds List</h1>
    {% if breed_list %}
    <ul>
        {% for breed in breed_list %}
           <li>
               {{ breed.name }}
                (<a href="{% url 'cats:breed_update' breed.id %}">Update</a> |
                <a href="{% url 'cats:breed_delete' breed.id %}">Delete</a>) <br/>
            </li>
        {% endfor %}
    </ul>
    {% else %}
        <p>There are no breeds in the library.</p>
    {% endif %}
    <!-- Rest of page -->
    <p><a href="{% url 'cats:breed_create' %}">Add a breed</a></p>
    <p><a href="{% url 'cats:all' %}">Back to cats</a></p>
{% endblock %}

mysite/cats/templates/cats/cat_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Delete Cat</h1>

<p>Are you sure you want to delete the cat: {{ cat }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

mysite/cats/templates/cats/cat_form.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <br/>
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <br/>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'cats:all' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

mysite/cats/templates/cats/cat_list.html
{% extends "base_bootstrap.html" %}

{% block content %}
    <!-- List of Cats -->
    <h1>Cats List</h1>
    <p>This is an application to maintain a list of cats.</p>
    {% if cat_list %}
    <ul>
        {% for cat in cat_list %}
           <li>
               {{ cat.nickname }} ({{ cat.breed }})
                (<a href="{% url 'cats:cat_update' cat.id %}">Update</a> |
                <a href="{% url 'cats:cat_delete' cat.id %}">Delete</a>) <br/>
                Foods: {{ cat.foods }} <br/> Weight: {{ cat.weight }} kg <br/>
                Image: <a href={{ cat.image }}> Image of {{ cat.nickname }}</a>
            </li>
        {% endfor %}
    </ul>
    {% else %}
        <p>There are no cats in the library.</p>
    {% endif %}
    <!-- Rest of page -->
    <p>
    {% if breed_count > 0 %}
        <a href="{% url 'cats:cat_create' %}">Add a cat</a>
    {% else %}
        Please add a breed before you add a cat.
    {% endif %}
    </p>
    <p><a href="{% url 'cats:breed_list' %}">View breeds</a> ({{ breed_count }}) |
    <a href="{% url 'cats:breed_create' %}">Add a breed</a></p>
{% endblock %}